### ISSUE TITLE
[FEATURE] support folia

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [EpsilonNetWorkGroup/scccpdebris#2]
Nice plugin, so plz support folia to make it even cooler ;>

**Comment by D3it7i** [comment]
It looks like ProtocolLib support for folia is ready and I can make a test version.

**Comment by D3it7i** [comment]
[https://github.com/EpsilonNetWorkGroup/scccpdebris/releases/tag/1.20.4-v2](https://github.com/EpsilonNetWorkGroup/scccpdebris/releases/tag/1.20.4-v2)

**Comment by xiaoyueyoqwq** [comment]
> https://github.com/EpsilonNetWorkGroup/scccpdebris/releases/tag/1.20.4-v2

Hi there, I just recived a ERROR logs on my server, can you help and check it?
https://paste.ubuntu.com/p/5t9dghnHW3/

**Comment by D3it7i** [comment]
Spigot does not allow calling getEntities on an asynchronous thread. But in fact, folia has no concept of a main thread.
I moved the getEntity to the GlobalRegionScheduler run on folia, try this version: https://github.com/EpsilonNetWorkGroup/scccpdebris/actions/runs/9380169266

**Comment by xiaoyueyoqwq** [comment]
> Spigot does not allow calling getEntities on an asynchronous thread. But in fact, folia has no concept of a main thread. I moved the getEntity to the GlobalRegionScheduler run on folia, try this version: https://github.com/EpsilonNetWorkGroup/scccpdebris/actions/runs/9380169266

Okay, I will keep testing
